# configs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "production"
  PORT: "5000"
  REQUEST_TIMEOUT: "60"
  PROMETHEUS_PORT: "8000"
  
  # OpenSense
  API_URL: "https://api.opensensemap.org"
  BOXES_OFFSET_HOURS: "-1"
  
  # Valkey
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  VALKEY_EXP: "300"
  
  # MinIO
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_BUCKET_NAME: "sensebox-data"
  MINIO_SECURE: "False"