apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project
        image: omarmhawash/devops-project:0.4
        ports:
        - containerPort: 80
