# flask-api.yaml
apiVersion: v1
kind: Service
metadata:
  name: devops-project
  namespace: default  # Change if necessary
  labels:
    app: devops-project
    component: api
spec:
  selector:
    app: devops-project
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      # name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
  namespace: default  # Change if necessary
  labels:
    app: devops-project
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
      annotations:
        description: "Deployment of the DevOps project API"
    spec:
      containers:
        - name: devops-project
          image: omarmhawash/devops-project:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: api-credentials
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
