apiVersion: v1
kind: Service
metadata:
  name: devops-project
spec:
  selector:
    app: devops-project
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-project-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - localhost
    secretName: devops-project-tls
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-project
            port:
              number: 443 # Use the same port as the service