name: Development check
run-name: ${{ github.actor }} pushing changes to ${{ github.head_ref }}
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  test:
    name: Development check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - run: echo "new job triggered by ${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - name: Setup python v${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies...
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linting using pylint...
        run: |
          pip install pylint
          pylint $(git ls-files '*.py')
      - name: Testing using pytest...
        run: |
          pip install pytest pytest-cov
          pytest tests.py
      - run: echo "job status is ${{ job.status }}."
